### ISSUE TITLE
The size of tensor a (66) must match the size of tensor b (65) at non-singleton dimension 3

### ISSUE THREAD

**Issue by ls577** [yadongJiang/En_bisenetv2#1]
/home/lin/biseGit/En_bisenetv2/venv/lib/python3.6/site-packages/thop/vision/basic_hooks.py:92: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  kernel = torch.DoubleTensor([*(x[0].shape[2:])]) // torch.DoubleTensor(list((m.output_size,))).squeeze()
7.67G 2.88M
voc root /home/lin/biseGit/En_bisenetv2/dataset/VOCdevkit/VOC2012
split_f :  /home/lin/biseGit/En_bisenetv2/dataset/VOCdevkit/VOC2012/ImageSets/Segmentation/train.txt
voc root /home/lin/biseGit/En_bisenetv2/dataset/VOCdevkit/VOC2012
split_f :  /home/lin/biseGit/En_bisenetv2/dataset/VOCdevkit/VOC2012/ImageSets/Segmentation/val.txt
Dataset: voc, Train set: 1464, Val set: 1449
/home/lin/biseGit/En_bisenetv2/venv/lib/python3.6/site-packages/torch/nn/modules/loss.py:217: UserWarning: NLLLoss2d has been deprecated. Please use NLLLoss instead as a drop-in replacement and see https://pytorch.org/docs/master/nn.html#torch.nn.NLLLoss for more details.
  warnings.warn("NLLLoss2d has been deprecated. "
/home/lin/biseGit/En_bisenetv2/venv/lib/python3.6/site-packages/torch/nn/_reduction.py:42: UserWarning: size_average and reduce args will be deprecated, please use reduction='mean' instead.
  warnings.warn(warning.format(ret))
[!] Retrain
/home/lin/biseGit/En_bisenetv2/venv/lib/python3.6/site-packages/torchvision/transforms/functional.py:405: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  "Argument interpolation should be of type InterpolationMode instead of int. "
/home/lin/biseGit/En_bisenetv2/venv/lib/python3.6/site-packages/torchvision/transforms/functional.py:405: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  "Argument interpolation should be of type InterpolationMode instead of int. "
Traceback (most recent call last):
  File "./tools/train.py", line 177, in <module>
    main()
  File "./tools/train.py", line 137, in main
    outputs, aux_out0, aux_out1, aux_out2 = model(images)
  File "/home/lin/biseGit/En_bisenetv2/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lin/biseGit/En_bisenetv2/venv/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/lin/biseGit/En_bisenetv2/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "./core/en_bisenetv2.py", line 21, in forward
    feat_head = self.bga(detail, feat8)
  File "/home/lin/biseGit/En_bisenetv2/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "./core/utils.py", line 425, in forward
    detail = segout_feat_left.sigmoid() * detail_feat
RuntimeError: The size of tensor a (66) must match the size of tensor b (65) at non-singleton dimension 3

**Comment by ls577** [comment]
so sad!The size of tensor a (66) must match the size of tensor b (65) at non-singleton dimension 3

**Comment by ls577** [comment]
if feat16.size(2) % 2 == 0:
            w = 2 * feat16.size(2)
            h = 2 * feat16.size(3)
        else:
            w = 2 * feat16.size(2) - 1
            h = 2 * feat16.size(3) -1

**Comment by lmcggg** [comment]
> if feat16.size(2) % 2 == 0: w = 2 * feat16.size(2) h = 2 * feat16.size(3) else: w = 2 * feat16.size(2) - 1 h = 2 * feat16.size(3) -1

Where should I put this code? I tried adding it at the end of the SegmentBranch（） but it didn't work. By the way, isn't the BGA () input parameter feat8? Why change the size of feat16?

**Comment by azuredsky** [comment]
change the utils/opts.py  crop_size 513 to 640
parser.add_argument("--crop_size", type=int, default=640)
